
### WEATHER
  weather:
    name: 'Weather'
    control: 'hidden'
    entities:
      - weather.dark_sky
      - weather.met_office_greengates
      - weather.openweathermap
      - weather.yweather
      