
### MEDIA
  media_shield_all:
    name: "SHIELD"
    control: 'hidden'
    entities:
      - media_player.shield_all

  media_sonos_all:
    name: "SONOS"
    control: 'hidden'
    entities:
      - media_player.sonos_all
