
### HUE
  hue_lights_outside:
    name: "Hue Outside Lights"
    entities:
      - light.hue_front_porch

  hue_lights_living_room:
    name: "Hue Living Room Lights"
    entities:
      - light.hue_big_floor_lamp
      - light.hue_small_floor_lamp
      - light.hue_table_lamp
      - light.hue_tv_backlight

  hue_lights_all:
    name: "Hue Lights All"
    control: hidden
    entities:
      - switch.hue_lights_living_room
      - switch.hue_lights_outside
      - light.hue_living_room_all
      - light.hue_outside_all
      - light.hue_big_floor_lamp
      - light.hue_small_floor_lamp
      - light.hue_table_lamp
      - light.hue_tv_backlight
      - light.hue_front_porch

  hue_light_inputs:
    name: "Hue Lights Input"
    control: hidden
    entities:
      - input_boolean.hue_lights_living_room_dim
      - input_boolean.hue_lights_living_room_full
      - input_boolean.hue_lights_living_room_movie
      - input_boolean.hue_lights_living_room_morning
      - input_boolean.hue_lights_living_room_white
      - input_boolean.hue_lights_living_room_night
      - input_boolean.hue_lights_living_room_off
      - input_boolean.hue_lights_outside_full
      - input_boolean.hue_lights_outside_dim
      - input_boolean.hue_lights_outside_off

  hue_light_scripts:
    name: "Hue Lights Scripts"
    control: hidden
    entities:
      - script.hue_lights_living_room_dim
      - script.hue_lights_living_room_full
      - script.hue_lights_living_room_movie
      - script.hue_lights_living_room_morning
      - script.hue_lights_living_room_white
      - script.hue_lights_living_room_night
      - script.hue_lights_living_room_off
      - script.hue_lights_outside_full
      - script.hue_lights_outside_dim
      - script.hue_lights_outside_off
