
### VIEWS
### PAGE 1
  default_view:
    name: 'Home'
    view: true
    entities:
      - group.page_one_today
      - group.page_one_home
      - group.page_one_info
      - group.hue_lights_living_room
      - group.hue_lights_outside
      - group.hue_light_scripts
      - group.media_shield_all
      - group.media_sonos_all

#### PAGE 2
  Page_2:
    name: "Page 2"
    view: true
    entities:
      - group.page_two_media_sonos_select_music
      - media_player.shield_all
      - media_player.sonos_all
      - media_player.sony_bravia
      - media_player.emby_shield
      - media_player.plex_shield
      - media_player.cast_shield
      - media_player.kodi_kodi
      - media_player.sonos_living_room
      - media_player.sonos_kitchen
      - media_player.sonos_bedroom

### PAGE 3
  Page_3:
    name: "Page 3"
    view: true
    entities:
      - group.page_three_test_things
      - group.page_three_config
      - group.page_three_guest_mode
      - group.page_three_input_enables
      - group.docker_homeassistant
      - group.hue_light_scripts
      - group.hue_light_inputs
      - group.hue_lights_all
      - group.presence_james
      - group.presence_gillian

### DOCKER
  docker:
    name: 'Docker'
    control: hidden
    view: true
    entities:
      - group.docker_restart_all
      - group.docker_switches_all
      - group.docker_homeassistant
