
### INPUT_SELECT
### SONOS
  media_sonos_select_source:
    name: "Sonos Source"
    options:
      - 'None'
      - "Sea Waves"
      - 'Weightless'
      - "BBC 6 MUSIC"
    initial: 'None'

### HUE
### HUE SCENE SELECT
  hue_select_scene_living_room:
    name: "Select Scene"
    options:
      - 'None'
      - 'Full'
      - 'Dim'
      - 'Movie'
      - 'White'
      - 'Night'
    initial: 'None'

  hue_select_scene_outside:
    name: "Select Scene"
    options:
      - 'None'
      - 'Full'
      - 'Dim'
    initial: 'None'
