
### INPUT
### MISCELLANEOUS
### DISABLE
  misc_disable_bedtime:
    name: "Disable Bedtime Automation"
### ENABLE
  misc_enable_at_home:
    name: "Enable At Home"
  misc_enable_guest_mode:
    name: "Enable Guest Mode"
  misc_enable_time_for_bed:
    name: "Enable Time for Bed"
    initial: off

### MEDIA
  media_shield_enable_lights:
    name: "Enable Shield Lights"
