
### INPUT BOOLEAN
### GUEST MODE
  guest_mode_enable:
    name: "Enable Guest Mode"

### NIGHT MODE
  night_mode_enable:
    name: "Enable Night Mode"

### ENABLE SHIELD AUTOMATIONS
  media_shield_enable_lights:
    name: "Enable Shield"
