
### ZONES
### HOME
- name: 'Home'
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  radius: '150'
  icon: mdi:home-map-marker

### WORK
- name: 'Work'
  latitude: !secret latitude_work
  longitude: !secret longitude_work
  radius: '150'
  icon: mdi:account-multiple
