
### BASIC CONFIG
homeassistant:
  name: No. 33
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home
  unit_system: metric
  time_zone: Europe/London
  whitelist_external_dirs:
    - !secret folder_1

### ADDITIONAL CONFIG
updater:
config:
sun:
map:
frontend:
  javascript_version: latest

logger:
  default: warning

system_log:
  max_entries: 25

history: !include include/history/history.yaml
logbook: !include include/history/logbook.yaml
recorder: !include include/history/recorder.yaml

http:
  api_password: !secret api_password
  trusted_networks:
    - !secret trusted_ip_1
    - !secret trusted_ip_2
    - !secret trusted_ip_3
    - !secret trusted_ip_4
  ip_ban_enabled: true
  login_attempts_threshold: 5

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

custom_updater:
  component_urls:
    - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json
  card_urls:
    - https://raw.githubusercontent.com/kuuji/button-card/0.0.2/tracker.json

### INCLUDE
automation: !include include/automation.yaml
binary_sensor: !include include/binary_sensor.yaml
#cloud: !include include/cloud.yaml
device_tracker: !include include/device_tracker.yaml
folder_watcher: !include include/folder_watcher.yaml
#homekit: !include include/homekit.yaml
hue: !include include/hue.yaml
input_boolean: !include include/input_boolean.yaml
input_select: !include include/input_select.yaml
light: !include include/light.yaml
media_player: !include include/media_player.yaml
#mqtt: !include include/mqtt.yaml
notify: !include include/notify.yaml
script: !include include/script.yaml
sensor: !include include/sensor.yaml
shell_command: !include include/shell_command.yaml
switch: !include include/switch.yaml
tado: !include include/tado.yaml
telegram_bot: !include include/telegram_bot.yaml
timer: !include include/timer.yaml
weather: !include include/weather.yaml
zone: !include include/zone.yaml
