
### HUE
### NATIVE HUE SCENES
  hue_lights_living_room_dim:
    alias: "Living Room Dim"
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Living Room Dim"

  hue_lights_living_room_full:
    alias: "Living Room Full"
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Living Room Full"

  hue_lights_living_room_morning:
    alias: "Living Room Morning"
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Living Room Dim"

  hue_lights_living_room_movie:
    alias: "Living Room Movie"
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Living Room Movie"

  hue_lights_living_room_night:
    alias: "Living Room Night"
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Living Room Night"

  hue_lights_living_room_white:
    alias: "Living Room White"
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Living Room White"

  hue_lights_outside_full:
    alias: "Outside Full"
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: 'Outside'
          scene_name: "Outside Full"

  hue_lights_outside_dim:
    alias: "Outside Dim"
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: 'Outside'
          scene_name: "Outside Dim"

### TURN OFF THE LIGHTS
  hue_lights_outside_off:
    alias: "Outside Off"
    sequence:
      - service:  light.turn_off
        entity_id:
          - light.hue_outside_all
        data:
          transition: '2'

  hue_lights_living_room_off:
    alias: "Living Room Off"
    sequence:
      - service:  light.turn_off
        entity_id:
          - light.hue_living_room_all
        data:
          transition: '2'
