
### HUE
  hue_motion_start_timer:
    alias: "Start Hue Timer"
    sequence:
      - service: timer.start
        entity_id: timer.hue_motion

  hue_motion_pause_timer:
    alias: "Pause Hue Timer"
    sequence:
      - service: timer.pause
        entity_id: timer.hue_motion

  hue_motion_cancel_timer:
    alias: "Cancel Hue Timer"
    sequence:
      - service: timer.cancel
        entity_id: timer.hue_motion

  hue_motion_finish_timer:
    alias: "Finish Hue Timer"
    sequence:
      - service: timer.finish
        entity_id: timer.hue_motion

### PLEX
  plex_paused_start_timer:
    alias: "Start Plex Timer"
    sequence:
      - service: timer.start
        entity_id: timer.media_plex

  plex_paused_pause_timer:
    alias: "Pause Plex Timer"
    sequence:
      - service: timer.pause
        entity_id: timer.media_plex

  plex_paused_cancel_timer:
    alias: "Cancel Plex Timer"
    sequence:
      - service: timer.cancel
        entity_id: timer.media_plex

  plex_paused_finish_timer:
    alias: "Finish Plex Timer"
    sequence:
      - service: timer.finish
        entity_id: timer.media_plex
