
### MEDIA
### SHIELD SHOW GROUP
  media_shield_group_show:
    alias: "Shield Playing Show Group"
    sequence:
      - service: group.set_visibility
        entity_id:
          - group.media_shield_all
        data:
          visible: 'True'

### SHIELD HIDE GROUP
  media_shield_group_hide:
    alias: "Hide Shield Group"
    sequence:
      - service: group.set_visibility
        entity_id:
          - group.media_shield_all
        data:
          visible: 'False'

### SHIELD PAUSES SONOS
  media_shield_playing_sonos_pause:
    alias: "Shield Playing Pause Sonos"
    sequence:
      - service: media_player.media_pause
        data:
          entity_id:
            - media_player.sonos_living_room
            - media_player.sonos_kitchen
            - media_player.sonos_bedroom

### SHIELD ENABLE LIGHTS
  media_shield_enable_lights:
    alias: "Shield Enable Lights"
    sequence:
      - service: input_boolean.turn_on
        data:
          entity_id:
            - input_boolean.media_shield_enable_lights
