
### MEDIA
### SHIELD PAUSES SONOS
  media_shield_playing_sonos_pause:
    alias: "Shield Playing Pause Sonos"
    sequence:
      - service: media_player.media_pause
        data:
          entity_id:
            - media_player.sonos_living_room
            - media_player.sonos_kitchen
            - media_player.sonos_bedroom

### SHIELD ENABLE LIGHTS
### USEFUL FOR TESTING AUTOMATIONS BEFORE SUNSET
  media_shield_enable_lights:
    alias: "Shield Enable Lights"
    sequence:
      - service: input_boolean.turn_on
        data:
          entity_id:
            - input_boolean.media_shield_enable_lights
