
### DOCKER
### EMBY
  docker_restart_emby:
    alias: "Restart Emby"
    sequence:
      - service: shell_command.docker_restart_emby

### HA DOCKERMON
  docker_restart_hadockermon:
    alias: "Restart HA Dockermon"
    sequence:
      - service: shell_command.docker_restart_hadockermon

### HOMEASSISTANT
  docker_restart_homeassistant:
    alias: "Restart Homeassistant"
    sequence:
      - service: shell_command.docker_restart_homeassistant

### NZBGET
  docker_restart_nzbget:
    alias: "Restart NZBGet"
    sequence:
      - service: shell_command.docker_restart_nzbget

### PLEX
  docker_restart_plex:
    alias: "Restart Plex"
    sequence:
      - service: shell_command.docker_restart_plex

### RADARR
  docker_restart_radarr:
    alias: "Restart Radarr"
    sequence:
      - service: shell_command.docker_restart_radarr

### SONARR
  docker_restart_sonarr:
    alias: "Restart Sonarr"
    sequence:
      - service: shell_command.docker_restart_sonarr

### WATCHTOWER
  docker_restart_watchtower:
    alias: "Restart Watchtower"
    sequence:
      - service: shell_command.docker_restart_watchtower

### HA-DOCKERMON
  docker_restart_dockermon:
    alias: "Restart Dockermon"
    sequence:
      - service: shell_command.docker_restart_dockermon
