
### HUE
### HUE SELECT SCENE
- alias: 'hue_select_scene_living_room'
  id: hue_select_scene_living_room
  initial_state: 'True'
  trigger:
    - platform: state
      entity_id:
        - input_select.hue_select_scene_living_room
  action:
    - service: hue.hue_activate_scene
      data_template:
        group_name: "Living Room"
        scene_name: "Living Room {{ states.input_select.hue_select_scene_living_room.state }}"

- alias: 'hue_select_scene_outside'
  id: hue_select_scene_outside
  initial_state: 'True'
  trigger:
    - platform: state
      entity_id:
        - input_select.hue_select_scene_outside
  action:
    - service: hue.hue_activate_scene
      data_template:
        group_name: "Outside"
        scene_name: "Outside {{ states.input_select.hue_select_scene_outside.state }}"

