
### HUE
### NOTIFY MOTION DETECTED
- alias: 'hue_motion_living_room_night'
  id: hue_motion_living_room_night
#  initial_state: 'True'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.hue_motion_living_room
      to: 'on'
  condition:
    - condition: template
      value_template: >
        {{ is_state('sensor.time_of_day', 'Night') or
        is_state('input_boolean.night_mode_enable', 'on') }}
  action:
    - service: script.hue_lights_living_room_night
    - delay: '00:00:01'
    - service: script.hue_motion_cancel_timer
    - delay: '00:00:01'
    - service: script.hue_motion_start_timer

### HUE MOTION TIMER ENDED
- alias: 'hue_motion_timer_ended'
  id: hue_motion_timer_ended
#  initial_state: 'True'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.hue_motion
  condition:
    - condition: template
      value_template: >
        {{ is_state('sensor.time_of_day', 'Night') or
        is_state('input_boolean.night_mode_enable', 'on') }}
  action:
    - service: script.hue_lights_living_room_off

### NOTIFY TAP PRESS
- alias: 'hue_tap_living_room_notify'
  id: hue_tap_living_room_notify
  initial_state: 'True'
  trigger:
    - platform: state
      entity_id:
        - sensor.hue_tap_button
  action:
    - service: notify.get_notified
      data_template:
        message: "{{ trigger.to_state.state }} has been pressed"
        title: "Hue Tap {{ trigger.to_state.state }}"
