
### HUE
### LIGHTS ON OUTSIDE AM
- alias: 'hue_lights_outside_full_am'
  id: hue_lights_outside_full_am
#  initial_state: 'True'
  trigger:
    - platform: time
      at: '05:30:00'
  action:
    - service: script.hue_lights_outside_full

### LIGHTS ON OUTSIDE PM
- alias: 'hue_lights_outside_full_pm'
  id: hue_lights_outside_full_pm
#  initial_state: 'True'
  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-1:00:00'
  action:
    - service: script.hue_lights_outside_full

### LIGHTS DIM OUTSIDE PM
- alias: 'hue_lights_outside_dim'
  id: hue_lights_outside_dim
#  initial_state: 'True'
  trigger:
    - platform: time
      at: '22:30:00'
  action:
    - service: script.hue_lights_outside_dim

### LIGHTS OFF OUTSIDE AM
- alias: 'hue_lights_outside_off_am'
  id: hue_lights_outside_off_am
  initial_state: 'True'
  trigger:
    - platform: time
      at: '08:30:00'
  action:
    - service: script.hue_lights_outside_off

### LIGHTS OFF OUTSIDE PM
- alias: 'hue_lights_outside_off_pm'
  id: hue_lights_outside_off_pm
#  initial_state: 'True'
  trigger:
    - platform: time
      at: '23:30:00'
  action:
    - service: script.hue_lights_outside_off
