
### SONOS
### SONOS SELECT  MUSIC
- alias: 'media_sonos_select_music'
  id: media_sonos_select_music
  initial_state: 'True'
  trigger:
    - platform: state
      entity_id:
        - input_select.media_sonos_select_source
  action:
    - service_template: >
        {% if is_state('input_select.media_sonos_select_source', "BBC 6 MUSIC") %}
          script.media_sonos_select_6music
        {% elif is_state('input_select.media_sonos_select_source', "Sea Waves") %}
          script.media_sonos_select_waves
        {% elif is_state('input_select.media_sonos_select_source', "Weightless") %}
          script.media_sonos_select_weightless
        {% endif %}
