
### MISCELLANEOUS
### DAILY RESET
- alias: 'misc_daily_reset'
  id: misc_daily_reset
  initial_state: 'True'
  trigger:
    - platform: time
      at: '02:00:00'
  condition:
    - condition: template
      value_template: "{{ is_state('input_boolean.misc_enable_guest_mode', 'off') }}"
  action:
    - service: script.misc_daily_reset

### GUEST MODE ON
- alias: 'misc_guest_mode_on'
  id: misc_guest_mode_on
  initial_state: 'True'
  trigger:
    - platform: state
      entity_id:
        - input_boolean.misc_enable_guest_mode
      to: 'on'
    - platform: event
      event_type: 'telegram_command'
      event_data:
        command: '/guest_on'
  action:
    - service: script.misc_guest_mode

### GUEST MODE OFF
- alias: 'misc_guest_mode_off'
  id: misc_guest_mode_off
  initial_state: 'True'
  trigger:
    - platform: state
      entity_id:
        - input_boolean.misc_enable_guest_mode
      to: 'off'
    - platform: event
      event_type: 'telegram_command'
      event_data:
        command: '/guest_off'
  action:
    - service: script.misc_daily_reset
    - service: notify.get_notified
      data:
        message: "Automations have been re-enabled"
        title: "Guest Mode Disabled"

### BEDTIME ON
- alias: 'misc_time_for_bed_on'
  id: misc_time_for_bed_on
  initial_state: 'True'
  trigger:
    - platform: state
      entity_id:
        - input_boolean.misc_enable_time_for_bed
      to: 'on'
  action:
    - service: script.misc_time_for_bed
    - service: notify.get_notified
      data:
        message: 'Goodnight!'
