
### CONFIG
### RESTART
- alias: 'config_docker_restart_hass'
  id: config_docker_restart_hass
  initial_state: 'True'
  trigger:
    - platform: event
      event_type: 'telegram_command'
      event_data:
        command: '/restart'
  action:
    - service: script.docker_restart_homeassistant

### PURGE DATABASE
- alias: 'config_purge_database'
  id: config_purge_database
  initial_state: 'True'
  trigger:
    - platform: event
      event_type: 'telegram_command'
      event_data:
        command: '/purge'
  action:
    - service: script.config_clear_error_log
    - delay: '00:00:01'
    - service: script.config_purge_database_keep_1_day

### START HOMEKIT
- alias: 'config_start_homekit'
  id: config_start_homekit
  initial_state: 'False'
  trigger:
    - platform: homeassistant
      event: 'start'
  action:
    - delay: '00:02:00'
    - service: script.config_homekit_start
