
### HUE
### NOTIFY MOTION DETECTED
- alias: 'hue_motion_living_room'
  id: hue_motion_living_room
  initial_state: 'True'
  trigger:
    - platform: state
      entity_id:
        - sensor.motion_hue_living_room
      to: 'on'
  condition:
    condition: template
    value_template: >
      {{ is_state('binary_sensor.bayesian_presence_james', 'off') and 
      is_state('binary_sensor.bayesian_presence_gillian', 'off') or 
      is_state('sensor.time_of_day', 'Night') and 
      is_state('light.hue_living_room_all', 'on') }}
  action:
    - service_template: >
        {% if is_state('binary_sensor.bayesian_presence_james', 'off') and
        is_state('binary_sensor.bayesian_presence_gillian', 'off') %}
          script.hue_motion_living_room_notify
        {% endif %}
    - service_template: >
        {% if is_state('sensor.time_of_day', 'Night') and
        is_state('light.hue_living_room_all', 'off') %}
          script.hue_lights_living_room_night
        {% endif %}

### NOTIFY TAP PRESS
- alias: 'hue_tap_living_room_notify'
  id: hue_tap_living_room_notify
  initial_state: 'True'
  trigger:
    - platform: state
      entity_id:
        - sensor.hue_tap
  action:
    - service: notify.get_notified
      data_template:
        message: "{{ trigger.to_state.state }} has been pressed"
        title: "Hue Tap {{ trigger.to_state.state }}"
