
### GUEST MODE ON
- alias: 'guest_mode_enable'
  id: guest_mode_enable
  initial_state: 'True'
  trigger:
    - platform: state
      entity_id:
        - input_boolean.guest_mode_enable
      to: 'on'
    - platform: event
      event_type: 'telegram_command'
      event_data:
        command: '/guest_on'
  action:
    - service: script.guest_mode_automations_off
    - delay: '00:00:01'
    - service: notify.get_notified
      data:
        message: "Automations have been disabled"
        title: "Guest Mode ON"

### GUEST MODE OFF
- alias: 'guest_mode_disable'
  id: guest_mode_disable
  initial_state: 'True'
  trigger:
    - platform: state
      entity_id:
        - input_boolean.guest_mode_enable
      to: 'off'
    - platform: event
      event_type: 'telegram_command'
      event_data:
        command: '/guest_off'
  action:
    - service: script.guest_mode_automations_on
    - delay: '00:00:01'
    - service: notify.get_notified
      data:
        message: "Automations have been re-enabled"
        title: "Guest Mode OFF"
