
### NOTIFY
### PING PONG
- alias: notify_ping_pong
  id: notify_ping_pong
  initial_state: 'True'
  trigger:
    - platform: event
      event_type: 'telegram_command'
      event_data:
        command: '/ping'
  action:
    - service: notify.bot
      data:
        message: 'pong'

### RESTARTED
- alias: notify_hass_restart
  id: notify_hass_restart
  initial_state: 'True'
  trigger:
    - platform: homeassistant
      event: 'start'
  action:
    - service: notify.get_notified
      data:
        message: "Home Assistant should now be available"
        title: "Hass Restarted"

### SHUTTING DOWN
- alias: notify_hass_shutdown
  id: notify_hass_shutdown
  initial_state: 'True'
  trigger:
    - platform: homeassistant
      event: 'shutdown'
  action:
    - service: notify.get_notified
      data:
        message: "Home Assistant is shutting down"
        title: "Hass Shutting Down"

### HOMEASSISTANT UPDATE
- alias: notify_hass_update
  id: notify_hass_update
  initial_state: 'True'
  trigger:
    - platform: state
      entity_id:
        - updater.updater
  condition:
    - condition: template
      value_template: >
        {{ not is_state("updater.updater", 'unknown' ) }}
  action:
    - service: notify.get_notified
      data:
        message: >
          Home Assistant {{ states("updater.updater") }}
          is now available. Go to https://home-assistant.io
        title: "Home Assistant Update"
