
### CUSTOMIZE
homeassistant:
### GLOBAL ENTITIES
  customize_glob:
    "script.docker*":
      icon: mdi:docker

### INDIVIDUAL ENTITIES
  customize:
 ### SENSORS
    sensor.hue_motion_battery:
      device_class: battery
    sensor.hue_motion_lux:
      icon: mdi:theme-light-dark
    sensor.solar_elevation:
      icon: mdi:elevation-rise
    sensor.hue_tap_button_pressed:
      icon: mdi:google-circles-communities

### BINARY SENSORS
    binary_sensor.bayesian_presence_james:
      entity_picture: /local/sw/poe.png
    binary_sensor.bayesian_presence_gillian:
      entity_picture: /local/sw/rey2.png
