
### HUE
### HUE HUB
hue:
  bridges:
    - host: !secret hue_ip
      filename: phue.conf
      allow_unreachable: 'True'
      allow_hue_groups: 'True'

### LIGHT GROUPS
light:
  - platform: group
    name: "Hue Outside All"
    entities:
      - light.hue_front_porch

  - platform: group
    name: "Hue Living Room All"
    entities:
      - light.hue_big_floor_lamp
      - light.hue_small_floor_lamp
      - light.hue_table_lamp
      - light.hue_tv_backlight

### HUE SENSORS
### CUSTOM COMPONENT
### ADDS HUE MOTION & HUE TAP
sensor:
  - platform: hue
    ip_address: !secret hue_ip
    token: !secret hue_token

### ### ADDS HUE MOTION BATTERY SENSOR
  - platform: template
    sensors:
      hue_motion_living_room_battery:
        friendly_name: "Hue Motion Sensor Battery"
        value_template: >
          {% if states.sensor.hue_motion_living_room_motion_sensor.attributes.battery is none %}
          Waiting
          {% else %}
          {{ states.sensor.hue_motion_living_room_motion_sensor.attributes.battery }}
          {% endif %}
        unit_of_measurement: '%'
