
### HUE
### HUB
hue:
  bridges:
    - host: !secret hue_ip
      filename: phue.conf
      allow_unreachable: 'True'
      allow_hue_groups: 'True'

### LIGHT GROUPS
light:
  - platform: group
    name: "Hue Outside All"
    entities:
      - light.hue_front_porch

  - platform: group
    name: "Hue Living Room All"
    entities:
      - light.hue_big_floor_lamp
      - light.hue_small_floor_lamp
      - light.hue_table_lamp
      - light.hue_tv_backlight

### SENSORS
sensor:
### MOTION - TEMP
  - platform: rest
    resource: !secret hue_motion_temp
    value_template: >
      {{ value_json.state.temperature | float / 100 }}
    unit_of_measurement: '°C'
    name: "Hue Motion Living Room Temperature"
    device_class: 'temperature'
### MOTION - BATTERY
  - platform: rest
    resource: !secret hue_motion_battery
    value_template: >
      {{ value_json.config.battery }}
    unit_of_measurement: '%'
    name: "Hue Motion Battery"
    device_class: 'battery'
### MOTION - LUX
  - platform: rest
    resource: !secret hue_motion_lightlevel
    value_template: >
      {{ value_json.state.lightlevel }}
    unit_of_measurement: 'Lux'
    name: "Hue Motion Lux"
    device_class: 'lux'
### TAP
  - platform: rest
    resource: !secret hue_tap
    value_template: >
      {% if value_json.state.buttonevent == 34 %}
        Button 1
      {% elif value_json.state.buttonevent == 16 %}
        Button 2
      {% elif value_json.state.buttonevent == 17 %}
        Button 3
      {% elif value_json.state.buttonevent == 18 %}
        Button 4
      {% else %}
        Unknown
      {% endif %}
    name: "Hue Tap Button"

### LIGHTS
### CURRENT SCENE LIVING ROOM
  - platform: template
    sensors:
      hue_lights_active_scene:
        friendly_name: "Active Scene"
        value_template: >
          {% if states.light.living_room.attributes.xy_color == (0.447, 0.406) and
          is_state('light.hue_table_lamp', 'off') %}
            Movie
          {% elif states.light.living_room.attributes.xy_color == (0.502, 0.414) and
          is_state('light.hue_table_lamp', 'on') %}
            Dim
          {% elif states.light.living_room.attributes.xy_color == (0.447, 0.406) and
          is_state('light.hue_table_lamp', 'on') %}
            Full
          {% elif states.light.living_room.attributes.xy_color == (0.314, 0.331) %}
            White
          {% elif states.light.living_room.attributes.xy_color == (0.429, 0.321) %}
            Night
          {% else %}
            None
          {% endif %}
        icon_template: >
          {% if is_state('sensor.hue_lights_active_scene', 'None') %}
            mdi:checkbox-multiple-marked-circle-outline
          {% else %}
            mdi:checkbox-multiple-marked-circle-outline
          {% endif %}
### CURRENT SCENE OUTSIDE
  - platform: template
    sensors:
      hue_lights_active_scene_outside:
        friendly_name: "Active Scene"
        value_template: >
          {% if states.light.outside.attributes.brightness == 127 %}
            Dim
          {% elif states.light.outside.attributes.brightness == 254 %}
            Full
          {% else %}
            None
          {% endif %}
        icon_template: >
          {% if is_state('sensor.hue_lights_active_scene_outside', 'None') %}
            mdi:checkbox-multiple-marked-circle-outline
          {% else %}
            mdi:checkbox-multiple-marked-circle-outline
          {% endif %}

### BINARY SENSORS
### MOTION
binary_sensor:
  - platform: rest
    resource: !secret hue_motion_motion
    value_template: >
      {{ value_json.state.presence }}
    scan_interval: 2
    name: "Hue Motion Living Room"
    device_class: 'motion'
### DAYLIGHT
  - platform: rest
    resource: !secret hue_motion_daylight
    value_template: >
      {{ value_json.state.daylight }}
    name: "Hue Motion Daylight"
    device_class: 'light'

### SWITCHES
### HUE OUTSIDE
switch:
  - platform: template
    switches:
      hue_lights_outside:
        friendly_name: "Hue Outside"
        value_template: >
          {{ is_state('light.hue_outside_all', 'on') }}
        turn_on:
          service: script.turn_on
          data:
            entity_id: script.hue_lights_outside_full
        turn_off:
          service: script.turn_on
          data:
            entity_id: script.hue_lights_outside_off
        icon_template: >
          {% if is_state('light.hue_outside_all', 'on') %}
            mdi:lightbulb-on
          {% else %}
            mdi:lightbulb
          {% endif %}
### HUE LIVING ROOM
      hue_lights_living_room:
        friendly_name: "Hue Living Room"
        value_template: >
          {{ is_state('light.hue_living_room_all', 'on') }}
        turn_on:
          service: script.turn_on
          data:
            entity_id: script.hue_lights_living_room_full
        turn_off:
          service: script.turn_on
          data:
            entity_id: script.hue_lights_living_room_off
        icon_template: >
          {% if is_state('light.hue_living_room_all', 'on') %}
            mdi:lightbulb-on
          {% else %}
            mdi:lightbulb
          {% endif %}
