
### SWITCHES
### HUE OUTSIDE
switch:
  - platform: template
    switches:
      hue_lights_outside:
        friendly_name: "Hue Outside"
        value_template: >
          {{ is_state('light.hue_outside_all', 'on') }}
        turn_on:
          service: script.hue_lights_outside_full
        turn_off:
          service: script.hue_lights_outside_off
        icon_template: >
          {% if is_state('light.hue_outside_all', 'on') %}
          mdi:lightbulb-on
          {% else %}
          mdi:lightbulb
          {% endif %}

### HUE LIVING ROOM
      hue_lights_living_room:
        friendly_name: "Hue Living Room"
        value_template: >
          {{ is_state('light.hue_living_room_all', 'on') }}
        turn_on:
          service: script.hue_lights_living_room_full
        turn_off:
          service: script.hue_lights_living_room_off
        icon_template: >
          {% if is_state('light.hue_living_room_all', 'on') %}
          mdi:lightbulb-on
          {% else %}
          mdi:lightbulb
          {% endif %}
