
### MEDIA
### PLEX
media_player:
  - platform: plex
    # entity_namespace: 'plex'
    scan_interval: 5
    include_non_clients: true
    remove_unavailable_clients: false
    # client_remove_interval: 600

### CAST
  - platform: cast
    entity_namespace: 'cast'
    host: !secret cast_ip

### KODI
  - platform: kodi
    entity_namespace: 'kodi'
    host: !secret cast_ip
    port: !secret kodi_port

### EMBY
  - platform: emby
    host: !secret emby_ip
    api_key: !secret emby_api

### SONY_BRAVIA_TV_PSK
### CUSTOM COMPONENT
  - platform: braviatv_psk
    name: "Sony Bravia"
    host: !secret sony_ip
    psk: !secret sony_psk
    mac: !secret sony_mac
    amp: True
    android: True
    sourcefilter:
      - HDMI

### UNIVERSAL
### COMBINES ALL MEDIA PLAYERS INTO A SINGLE ENTITY
  - platform: universal
    name: "SHIELD ALL"
    children:
      - media_player.plex_shield
      - media_player.cast_shield
      - media_player.kodi_kodi
      - media_player.emby_shield
