
### NOTIFY
### PUSHOVER
notify:
  - platform: pushover
    name: 'Pushover'
    api_key: !secret pushover_api
    user_key: !secret pushover_user
### TELEGRAM
  - platform: telegram
    name: 'bot'
    api_key: !secret telegram_api
    chat_id: !secret telegram_id
### SLACK
  - platform: slack
    name: 'slack'
    api_key: !secret slack_api
    default_channel: '#home-assistant'
    username: 'home-assistant'
    icon: 'bird'
### ALL-IN-ONE
  - platform: group
    name: 'get_notified'
    services:
      - service: 'pushover'
      # - service: 'slack'
      # - service: 'bot'

### TELEGRAM
### TELEGRAM BOT TO CONTROL HOMEASSISTANT
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_id
