
### NOTIFY
### PUSHOVER
notify:
  - platform: pushover
    name: 'Pushover'
    api_key: !secret pushover_api
    user_key: !secret pushover_user

### TELEGRAM
  - platform: telegram
    name: 'bot'
    api_key: !secret telegram_api
    chat_id: !secret telegram_id

### ALL-IN-ONE
### SINGLE ENTITY FOR ALL NOTIFY PLATFORMS
  - platform: group
    name: 'get_notified'
    services:
      - service: pushover

### TELEGRAM BOT
### TELEGRAM BOT TO CONTROL HOMEASSISTANT
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_id
