
### SENSORS
### TADO
tado:
  username: !secret tado_user
  password: !secret tado_pass

### TIME & DATE SENSOR
sensor:
  - platform: time_date
    display_options:
      - time
      - date

### UPTIME SENSOR
  - platform: uptime

### TODAY
  - platform: template
    sensors:
      today_all:
        friendly_name: 'Today'
        value_template: >
          {{ now().strftime('%a %d %b %Y') }}
        icon_template: >
          {% if is_state('sensor.today_all', 'unknown') %}
          mdi:calendar
          {%else%}
          mdi:calendar
          {% endif %}
      today_day:
        friendly_name: 'Day'
        value_template: >
          {{ now().strftime('%A') }}
      today_date:
        friendly_name: 'Date'
        value_template: >
          {{ now().strftime('%d') }}
      today_month:
        friendly_name: 'Month'
        value_template: >
          {{ now().strftime('%b') }}
      today_year:
        friendly_name: 'Year'
        value_template: >
          {{ now().strftime('%Y') }}

### MORNING, AFTERNOON, EVENING OR NIGHT
      time_of_day:
        friendly_name_template: >
          {% if is_state("sensor.time_of_day", 'Morning') %}
          Morning
          {% elif is_state("sensor.time_of_day", 'Afternoon') %}
          Afternoon
          {% elif is_state("sensor.time_of_day", 'Evening') %}
          Evening
          {% elif is_state("sensor.time_of_day", 'Night') %}
          Night
          {% elif is_state("sensor.time_of_day", 'Off') %}
          off
          {% endif %}
        icon_template: >
          {% if is_state("sensor.time_of_day", 'Morning') or
          is_state("sensor.time_of_day", 'Afternoon') or
          is_state("sensor.time_of_day", 'Evening') %}
          mdi:weather-partlycloudy
          {% elif is_state("sensor.time_of_day", 'Night') %}
          mdi:weather-night
          {% else %}
          mdi:timelapse
          {% endif %}
        value_template: >
          {% if now().strftime('%H:%M:%S') > ('00:00:00') and
          now().strftime('%H:%M:%S') < ('05:50:00') %}
          Night
          {% elif now().strftime('%H:%M:%S') > ('00:00:00') and
          now().strftime('%H:%M:%S') < ('12:00:00') %}
          Morning
          {% elif now().strftime('%H:%M:%S') > ('11:59:59') and
          now().strftime('%H:%M:%S') < ('18:00:00') %}
          Afternoon
          {% elif now().strftime('%H:%M:%S') > ('17:59:59') and
          now().strftime('%H:%M:%S') < ('22:15:00') %}
          Evening
          {% elif now().strftime('%H:%M:%S') > ('22:14:59') and
          now().strftime('%H:%M:%S') < ('23:59:59') %}
          Night
          {% else %}
          Off
          {% endif %}

### BINARY SENSORS
### WORKDAY
binary_sensor:
  - platform: workday
    country: 'UK'

### SUN
  - platform: template
    sensors:      
      allow_shield_lights:
        friendly_name: "Allow Shield Lights"
        value_template: >
          {{ now().strftime('%H:%M:%S') > ('17:30:00') or
          is_state('sun.sun', 'below_horizon') or
          is_state('input_boolean.media_shield_enable_lights', 'on') }}
