
### ZONES
zone:
  - name: 'Home'
    latitude: !secret latitude_home
    longitude: !secret longitude_home
    radius: '150'
    icon: mdi:home-map-marker

  - name: 'Work'
    latitude: !secret latitude_work
    longitude: !secret longitude_work
    radius: '150'
    icon: mdi:account-multiple

### DEVICE TRACKERS
### ASUSWRT
device_tracker:
### BLUETOOTH
  - platform: bluetooth_tracker
  - platform: asuswrt
    host: !secret asus_ip
    username: !secret asus_username
    password: !secret asus_password
    protocol: 'ssh'
    port: !secret asus_port

    consider_home: '00:10:00'
    interval_seconds: '00:02:00'
    new_device_defaults:
      track_new_devices: 'False'
      hide_if_away: 'False'

### TADO
  - platform: tado
    username: !secret tado_user
    password: !secret tado_pass
    home_id: !secret home_id

### BAYESIAN PRESENCE JAMES
binary_sensor:
  - platform: bayesian
    prior: 0.75
    name: "Bayesian Presence James"
    device_class: 'presence'
    probability_threshold: 0.95
    observations:
      - entity_id: "device_tracker.james_asus_oneplus3"
        prob_given_true: 0.6
        platform: 'state'
        to_state: 'home'
      - entity_id: "device_tracker.james_tado"
        prob_given_true: 0.8
        platform: 'state'
        to_state: 'home'
      - entity_id: "device_tracker.james_bt_oneplus3"
        prob_given_true: 0.8
        platform: 'state'
        to_state: 'home'

### BAYESIAN PRESENCE GILLIAN
  - platform: bayesian
    prior: 0.75
    name: "Bayesian Presence Gillian"
    device_class: 'presence'
    probability_threshold: 0.95
    observations:
      - entity_id: "device_tracker.gillian_asus_oneplus3t"
        prob_given_true: 0.8
        platform: 'state'
        to_state: 'home'
      - entity_id: "device_tracker.gillian_tado"
        prob_given_true: 0.8
        platform: 'state'
        to_state: 'home'
      - entity_id: "device_tracker.gillian_bt_oneplus3t"
        prob_given_true: 0.8
        platform: 'state'
        to_state: 'home'
